### ISSUE TITLE
Question about logging existing assignments

### ISSUE THREAD

**Issue by lukeasrodgers** [Shopify/verdict#19]
The way the event logger is currently set up means that existing assignments will be logged when using the `switch` method, which results in a lot of entries in our log files. For example, out of a 193K line log file, 171K are entries indicating that a subject has already been assigned to an experiment group.

As far as I can tell, these entries are not very important. Is there some reason to log them that I'm missing?

I would be happy to attempt a PR addressing this issue if it makes sense. One option would be to not log existing assignments at all. Alternatively, this could be a configurable option for the gem.

Thanks

**Comment by wvanbergen** [comment]
It really depends on how are you analyzing the results. The logging is just to build a dataset; what dataset you need depends on the kind of analysis you want to do. If it's not useful for your analysis, you can disable the logging.

**Comment by lukeasrodgers** [comment]
Sure, thanks, we'll do something like that. It just seemed to me like a) the logging of existing assignments is logspam, b) turning off all logging is explicitly discouraged in the README and doesn't fit with our use-case anyway, and c) there does not appear to be any straightforward way to turn off only some kinds of logging.

**Comment by wvanbergen** [comment]
This is why you can provide your own logger implementation. Normally you don't want to send this stuff to a file on disk. In our case, we have an implementation that sends all the events to a Kafka topic.
